# action.yml
name: 'Tanzu Mission Control Apply'
description: 'tmcctl apply'
inputs:
  tmc-api-key:  # id of input
    description: 'TMC API Key'
    required: true       
runs:
  using: 'docker'  
  image: 'docker://docker.io/ali5ter/tmc-gitops-play:0.0.2'
  args:
    - ${{ inputs.tmc-api-key }}