on: [push]

jobs:
  tmc_ctl_apply_job:
    runs-on: ubuntu-latest
    name: TMC Gitops apply
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Tanzu Mission Control Apply
        uses: ali5ter/tmc-gitops-play:0.0.1
        id: apply
        with:          
          tmc-api-key: ${{ secrets.TMC_API_TOKEN}}      