on: [push]

jobs:
  tmc_ctl_apply_job:
    runs-on: ubuntu-latest
    name: TMC Gitops apply
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ali5ter/tmc-gitops-play@v0.0.1
        id: apply
        with:          
          tmc-api-key: ${{ secrets.TMC_API_TOKEN }}      