on: [push]

jobs:
  tmc_ctl_apply_job:
    runs-on: ubuntu-latest
    name: TMC GitOps apply
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   fetch-depth: 1
        
      - name: TMC apply step
        # uses: ali5ter/tmc-gitops-play@v0.0.2
        uses: ./
        id: apply
        with:          
          tmc-api-key: ${{ secrets.TMC_API_TOKEN }}      